package com.tw.version2;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Before;
import org.junit.Test;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

import static org.fest.assertions.Assertions.assertThat;

public class LibraryTest2 {

    private Library2 library;
    private ByteArrayOutputStream outContent = new ByteArrayOutputStream();
    private ByteArrayInputStream inputStream;


    @Before
    public void setUp() {
        library = new Library2();
        System.setOut(new PrintStream(outContent));
    }

    public String systemOut() {
        return outContent.toString();
    }

    public void setInput(String input) {
        inputStream = new ByteArrayInputStream(input.getBytes());
        System.setIn(inputStream);
    }

    @Test
    public void testV2Input1AndWrong1AndRight1() {
        String inputString =
                "1\n"
                        +"错误输入\n"
                        + "张三,1,少数民族,5,数学: 75,语文: 95,英语: 80,编程: 80\n"
                        +"3\n";
        setInput(inputString);
        library.main();

        String result = "1. 添加学生\n" +
                "2. 生成成绩单\n" +
                "3. 退出请输入你的选择（1～3）：\n" +
                "请输入学生信息（格式：姓名, 学号, 民族, 班级, 学科: 成绩, ...），按回车提交：\n" +
                "请按正确的格式输入（格式：姓名, 学号, 民族, 班级, 学科: 成绩, ...）：\n"+
                "学生张三的成绩被添加\n" +
                "1. 添加学生\n" +
                "2. 生成成绩单\n" +
                "3. 退出请输入你的选择（1～3）：\n";

        assertThat(systemOut()).isEqualTo(result);
    }

    @Test
    public void testV2Input2AndScore() {
        String inputString =
                "1\n"
                        + "错误输入\n"
                        + "张三,1,少数民族,5,数学: 75,语文: 95,英语: 80,编程: 80\n"
                        + "2\n"
                        + "1\n"
                        + "3\n";
        setInput(inputString);
        library.main();

        String result = "1. 添加学生\n" +
                "2. 生成成绩单\n" +
                "3. 退出请输入你的选择（1～3）：\n" +
                "请输入学生信息（格式：姓名, 学号, 民族, 班级, 学科: 成绩, ...），按回车提交：\n" +
                "请按正确的格式输入（格式：姓名, 学号, 民族, 班级, 学科: 成绩, ...）：\n" +
                "学生张三的成绩被添加\n" +
                "1. 添加学生\n" +
                "2. 生成成绩单\n" +
                "3. 退出请输入你的选择（1～3）：\n" +
                "请输入要打印的学生的学号（格式： 学号, 学号,...），按回车提交：\n" +
                "成绩单\n" +
                "姓名|数学|语文|英语|编程|平均分|总分\n" +
                "========================\n" +
                "张三|75|95|80|80|85.0|340\n" +
                "========================\n" +
                "全班总分平均数：340.0\n" +
                "全班总分中位数：340.0\n" +
                "1. 添加学生\n" +
                "2. 生成成绩单\n" +
                "3. 退出请输入你的选择（1～3）：\n";

        assertThat(systemOut()).isEqualTo(result);
    }
}
